version: '3.4'

services:
  ticketing.app:
    image: ${DOCKER_REGISTRY-}ticketingapp
    depends_on:
      - "ticketing.db"
    container_name: ticketing.app
    build:
      context: .
      dockerfile: Ticketing.App/Dockerfile
    networks:
      - dev

  ticketing.db:
    image: postgres:latest
    container_name: ticketing.db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=Ticketing
      - POSTGRES_HOST_AUTH_METHOD=trust
    hostname: ticketing.db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - dev
    restart: unless-stopped

volumes:
  pgadmin:
    driver: local
  app_data:
    driver: local
networks:
  dev:
    driver: bridge
