// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ticketing.Infrastructure;

#nullable disable

namespace Ticketing.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240611131952_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ticketing.Domain.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArrivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Carrier")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CurrentStatusStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ShippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TrackingNumber", "Carrier")
                        .IsUnique();

                    b.ToTable("Shipments", "application");
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActionUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActionUserId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("Tickets", "core");
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("AccountType")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0afe7827-a0cf-47d4-9820-488d84b894b0"),
                            AccountType = (byte)1,
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "operations@bar.com",
                            Name = "foo",
                            PasswordHash = "y0hJNdP2TNzYp1JrFnO/PhrGL7BI567/OskMBZ/bjBzmlQND1AO3bTiYFTGlGcMmDRNfUbOVLytbH+K3k2FjYw==",
                            PasswordSalt = "6MonNb30kVohmzyk6hvpm9Pn7x66ATPe7DbEhUqeHAPZtL5xS8D29xEfs9lewyMKBQzAiYCH2aH5FpgH+Edd3Ov5Qk+rImsGdiN49W43SafAXsx5XFmRJs1UrJV6HgA70GrLpoZ//MJVH7DoKw7E8i1YhsIIzXb9m1Xr6EVGlYk=",
                            Updated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("30b3e2db-213c-4519-8dee-83b70133db35"),
                            AccountType = (byte)2,
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "it@bar.com",
                            Name = "bar",
                            PasswordHash = "y0hJNdP2TNzYp1JrFnO/PhrGL7BI567/OskMBZ/bjBzmlQND1AO3bTiYFTGlGcMmDRNfUbOVLytbH+K3k2FjYw==",
                            PasswordSalt = "6MonNb30kVohmzyk6hvpm9Pn7x66ATPe7DbEhUqeHAPZtL5xS8D29xEfs9lewyMKBQzAiYCH2aH5FpgH+Edd3Ov5Qk+rImsGdiN49W43SafAXsx5XFmRJs1UrJV6HgA70GrLpoZ//MJVH7DoKw7E8i1YhsIIzXb9m1Xr6EVGlYk=",
                            Updated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("df862849-2e4b-4f54-ae81-a8b55cf2fd17"),
                            AccountType = (byte)0,
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "undefined@bar.com",
                            Name = "foobar",
                            PasswordHash = "y0hJNdP2TNzYp1JrFnO/PhrGL7BI567/OskMBZ/bjBzmlQND1AO3bTiYFTGlGcMmDRNfUbOVLytbH+K3k2FjYw==",
                            PasswordSalt = "6MonNb30kVohmzyk6hvpm9Pn7x66ATPe7DbEhUqeHAPZtL5xS8D29xEfs9lewyMKBQzAiYCH2aH5FpgH+Edd3Ov5Qk+rImsGdiN49W43SafAXsx5XFmRJs1UrJV6HgA70GrLpoZ//MJVH7DoKw7E8i1YhsIIzXb9m1Xr6EVGlYk=",
                            Updated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Ticketing.Domain.Entities.User", "ActionUser")
                        .WithMany()
                        .HasForeignKey("ActionUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Ticketing.Domain.Entities.User", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Ticketing.Domain.Entities.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("ActionUser");

                    b.Navigation("CreateUser");

                    b.Navigation("Shipment");
                });
#pragma warning restore 612, 618
        }
    }
}
